class ValidationError(Exception): ...


class ValidationUserError(ValidationError): ...


class ValidationFirstNameError(ValidationError): ...


class ValidationSecondNameError(ValidationError): ...


class ValidationPhoneNumberError(ValidationError): ...


class ValidationEmailError(ValidationError): ...


class InputMessageError(Exception): ...


class InvalidSubKey(Exception): ...


class UserError(Exception): ...


class SubscriptionError(Exception): ...


class LessonError(Exception): ...


class ColumnCSVError(Exception): ...
